"""
backend/core/confidence.py
ConfidenceScorer — calculates a [0.0, 1.0] confidence score for any
LLM-generated clinical trial document section.

Score composition
─────────────────
    length_score        (0.0 – 0.45)   how long / detailed the response is
    structure_score     (0.0 – 0.20)   presence of clinical formatting signals
    coverage_score      (0.0 – 0.20)   section-type specific required keywords
    uncertainty_penalty (0.0 – 0.30)   hedging / uncertainty language found
    fallback_penalty    (0.0 – 0.15)   Groq fallback was used instead of Ollama
    template_penalty    (0.0 – 1.00)   response is clearly a template placeholder
                                        → hard-caps score at 0.10

All constants are defined at the top so they can be tuned without touching logic.
"""

from __future__ import annotations
import re
import logging
from dataclasses import dataclass, field
from typing import List, Optional
from backend.data.confidence_data import (
    STRUCTURE_PATTERNS, UNCERTAINTY_PHRASES, SECTION_COVERAGE
)
logger = logging.getLogger(__name__)

# ── Tunable constants ─────────────────────────────────────────────────────────

# Length thresholds (word count)
MIN_RESPONSE_LENGTH:  int   = 80     # below this → low confidence
TARGET_LENGTH:        int   = 300    # sweet spot start
MAX_RESPONSE_LENGTH:  int   = 700    # above this → full length credit
MAX_LENGTH_SCORE:     float = 0.50   # ceiling contribution from length

# Structure signal patterns
# Presence of any of these in the text earns +structure_per_hit up to MAX_STRUCTURE_SCORE

STRUCTURE_PER_HIT:   float = 0.04
MAX_STRUCTURE_SCORE: float = 0.20

# Uncertainty / hedging phrases — each hit penalises confidence

UNCERTAINTY_PER_HIT:   float = 0.10
MAX_UNCERTAINTY_SCORE: float = 0.30

# Penalties
FALLBACK_PENALTY: float = 0.12   # deducted when Groq 70B was used instead of Ollama
TEMPLATE_SCORE:   float = 0.08   # hard cap when response looks like a template

# Per-section minimum keyword coverage expectations
# dict[section_id → list[regex patterns expected to be present]]

COVERAGE_PER_HIT:   float = 0.05
MAX_COVERAGE_SCORE: float = 0.20


# ── Score breakdown dataclass ─────────────────────────────────────────────────

@dataclass
class ScoreBreakdown:
    """Full breakdown of how the confidence score was computed."""
    final:             float = 0.0
    length_score:      float = 0.0
    structure_score:   float = 0.0
    coverage_score:    float = 0.0
    uncertainty_penalty: float = 0.0
    fallback_penalty:  float = 0.0
    is_template:       bool  = False
    word_count:        int   = 0
    uncertainty_hits:  List[str] = field(default_factory=list)
    structure_hits:    int   = 0
    coverage_hits:     int   = 0
    coverage_total:    int   = 0

    def to_dict(self) -> dict:
        return {
            "final":              round(self.final, 4),
            "word_count":         self.word_count,
            "length_score":       round(self.length_score, 4),
            "structure_score":    round(self.structure_score, 4),
            "coverage_score":     round(self.coverage_score, 4),
            "uncertainty_penalty":round(self.uncertainty_penalty, 4),
            "fallback_penalty":   round(self.fallback_penalty, 4),
            "is_template":        self.is_template,
            "uncertainty_hits":   self.uncertainty_hits,
            "coverage_hits":      f"{self.coverage_hits}/{self.coverage_total}",
        }


# ── Main scorer class ─────────────────────────────────────────────────────────

class ConfidenceScorer:
    """
    Calculates a [0.0, 1.0] confidence score for a generated clinical
    trial document section.

    Usage:
        scorer = ConfidenceScorer()
        score  = scorer.score("intro", text, use_fallback=False)
        detail = scorer.score_with_breakdown("intro", text, use_fallback=False)
        avg    = scorer.evaluate_multiple_responses("intro", [text1, text2, text3])
    """

    # ── Public API ────────────────────────────────────────────────────────────

    def score(
        self,
        section_id:   str,
        response:     str,
        *,
        use_fallback: bool = False,
    ) -> float:
        """
        Return a single float in [0.0, 1.0].

        Args:
            section_id:   The section identifier (e.g. "intro", "statistics").
            response:     Raw text generated by the LLM.
            use_fallback: True if Groq was used instead of Ollama (applies penalty).
        """
        return self.score_with_breakdown(
            section_id, response, use_fallback=use_fallback
        ).final

    def score_with_breakdown(
        self,
        section_id:   str,
        response:     str,
        *,
        use_fallback: bool = False,
    ) -> ScoreBreakdown:
        """
        Return a ScoreBreakdown with all component scores and metadata.
        Use this when you want to log or surface the full explanation.
        """
        bd = ScoreBreakdown()

        # ── Guard: empty response ──────────────────────────────────────────
        if not response or not response.strip():
            bd.final = 0.0
            return bd

        # ── Guard: template / failure placeholder ─────────────────────────
        if self._is_template(response):
            bd.is_template = True
            bd.final = TEMPLATE_SCORE
            return bd

        words = response.split()
        bd.word_count = len(words)

        # ── Component scores ──────────────────────────────────────────────
        bd.length_score      = self._length_score(bd.word_count)
        bd.structure_score   = self._structure_score(response)
        bd.coverage_score    = self._coverage_score(section_id, response, bd)
        bd.uncertainty_penalty = self._uncertainty_penalty(response, bd)
        bd.fallback_penalty  = FALLBACK_PENALTY if use_fallback else 0.0

        # ── Combine ───────────────────────────────────────────────────────
        raw = (
            bd.length_score
            + bd.structure_score
            + bd.coverage_score
            - bd.uncertainty_penalty
            - bd.fallback_penalty
        )
        bd.final = round(max(0.0, min(raw, 1.0)), 4)

        logger.debug(
            f"Confidence [{section_id}]: {bd.final:.3f} "
            f"(len={bd.length_score:.2f} struct={bd.structure_score:.2f} "
            f"cov={bd.coverage_score:.2f} unc=-{bd.uncertainty_penalty:.2f} "
            f"fb=-{bd.fallback_penalty:.2f})"
        )
        return bd

    def evaluate_multiple_responses(
        self,
        section_id:   str,
        responses:    List[str],
        *,
        use_fallback: bool = False,
    ) -> float:
        """
        Score confidence from multiple candidate responses.

        Strategy:
          1. Score each response individually.
          2. Add a consistency bonus when responses agree closely.
          3. Return the score of the best response + consistency bonus.

        This mirrors the original evaluate_multiple_responses() pattern but
        produces a properly bounded [0.0, 1.0] result.
        """
        if not responses:
            return 0.0
        if len(responses) == 1:
            return self.score(section_id, responses[0], use_fallback=use_fallback)

        # Score all candidates
        scores = [
            self.score(section_id, r, use_fallback=use_fallback)
            for r in responses
        ]
        best_score = max(scores)
        best_text  = responses[scores.index(best_score)]

        # Consistency bonus: reward agreement between responses
        base_words = set(best_text.lower().split())
        consistency_bonus = 0.0
        for other in responses:
            if other == best_text:
                continue
            other_words = set(other.lower().split())
            if base_words and other_words:
                overlap = len(base_words & other_words) / len(base_words | other_words)
                # Each agreeing response adds up to +0.05 (Jaccard ≥ 0.7 → full bonus)
                consistency_bonus += min(0.05, overlap * 0.07)

        final = min(1.0, best_score + consistency_bonus)
        logger.debug(
            f"Multi-response confidence [{section_id}]: "
            f"best={best_score:.3f} consistency=+{consistency_bonus:.3f} "
            f"final={final:.3f} ({len(responses)} responses)"
        )
        return round(final, 4)

    # ── Internal helpers ──────────────────────────────────────────────────────

    @staticmethod
    def _is_template(text: str) -> bool:
        """True if the text is clearly a fallback/template placeholder."""
        lower = text.lower()
        markers = [
            "[template content",
            "[template —",
            "[generation failed",
            "set groq_api_key",
            "set ollama_api_key",
        ]
        return any(m in lower for m in markers)

    @staticmethod
    def _length_score(word_count: int) -> float:
        """
        Map word count to [0.0, MAX_LENGTH_SCORE].

        < MIN   → 0.0 (too short to be useful)
        MIN–TARGET → linear ramp from 0.0 to 0.35 × MAX
        TARGET–MAX → linear ramp from 0.35 × MAX to MAX
        > MAX   → MAX (longer is fine, no extra credit)
        """
        if word_count < MIN_RESPONSE_LENGTH:
            return 0.0
        if word_count >= MAX_RESPONSE_LENGTH:
            return MAX_LENGTH_SCORE
        if word_count <= TARGET_LENGTH:
            # fast ramp from MIN to TARGET
            t = (word_count - MIN_RESPONSE_LENGTH) / (TARGET_LENGTH - MIN_RESPONSE_LENGTH)
            return round(t * MAX_LENGTH_SCORE * 0.75, 4)
        # slower ramp from TARGET to MAX
        t = (word_count - TARGET_LENGTH) / (MAX_RESPONSE_LENGTH - TARGET_LENGTH)
        return round(MAX_LENGTH_SCORE * 0.75 + t * MAX_LENGTH_SCORE * 0.25, 4)

    @staticmethod
    def _structure_score(text: str) -> float:
        """Reward presence of clinical trial terminology and structure signals."""
        hits = sum(
            1 for pat in STRUCTURE_PATTERNS
            if re.search(pat, text, re.IGNORECASE)
        )
        score = min(hits * STRUCTURE_PER_HIT, MAX_STRUCTURE_SCORE)
        return round(score, 4)

    @staticmethod
    def _coverage_score(section_id: str, text: str, bd: ScoreBreakdown) -> float:
        """
        Check that section-specific required elements are present.
        Only sections with known patterns are evaluated; others get a neutral 0.10.
        """
        patterns = SECTION_COVERAGE.get(section_id)
        if not patterns:
            return 0.10  # neutral for sections we have no expectations for

        bd.coverage_total = len(patterns)
        hits = sum(
            1 for pat in patterns
            if re.search(pat, text, re.IGNORECASE)
        )
        bd.coverage_hits = hits
        score = min(hits * COVERAGE_PER_HIT, MAX_COVERAGE_SCORE)
        return round(score, 4)

    @staticmethod
    def _uncertainty_penalty(text: str, bd: ScoreBreakdown) -> float:
        """Penalise hedging / AI-limitation / uncertainty language."""
        lower = text.lower()
        hits  = []
        for pat in UNCERTAINTY_PHRASES:
            m = re.search(pat, lower, re.IGNORECASE)
            if m:
                hits.append(m.group(0)[:40])

        bd.uncertainty_hits = hits
        penalty = min(len(hits) * UNCERTAINTY_PER_HIT, MAX_UNCERTAINTY_SCORE)
        return round(penalty, 4)
